[build]
builder = "nixpacks"
buildCommand = """
composer install --optimize-autoloader --no-scripts --no-interaction && \
npm install && \
npm run build
"""

[deploy]
# single string (not array!)
preDeployCommand = """
php artisan cache:clear && \
php artisan route:clear && \
php artisan config:clear && \
php artisan view:clear && \
php artisan migrate --force --seed && \
php artisan shield:super-admin && \
npm install && npm run build
"""

startCommand = "php artisan serve --host=0.0.0.0 --port ${PORT}"

healthcheckPath = ""
