[build]
builder = "nixpacks"
buildCommand = """
composer install --optimize-autoloader --no-scripts --no-interaction && \
npm install && \
npm run build
"""

[deploy]
# single string (not array!)
preDeployCommand = """
composer dump-autoload && \
php artisan optimize:clear && \
php artisan filament:optimize && \
php artisan filament:assets && \
php artisan filament:cache-components && \
php artisan vendor:publish --force --tag=livewire:assets && \
php artisan migrate:fresh --force --seed && \
php artisan shield:super-admin && \
npm install && npm run build
"""

startCommand = "php artisan serve --host=0.0.0.0 --port ${PORT}"

healthcheckPath = ""
