[build]
builder = "nixpacks"
# Installer PHP deps + build assets
buildCommand = """
composer install --optimize-autoloader --no-scripts --no-interaction
npm install
npm run build
"""

[deploy]
# Créer la base sqlite + exécuter les migrations
preDeployCommand = [
    "mkdir -p database",
    "touch database/database.sqlite",
    "php artisan migrate --force",
]

# Lancer le serveur Laravel
startCommand = "php artisan serve --host=0.0.0.0 --port ${PORT}"

# Options santé
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
