[build]
builder = "nixpacks"
buildCommand = """
npm install && \
npm run build && \
composer install --optimize-autoloader --no-scripts --no-interaction
"""

[deploy]
# single string (not array!)
preDeployCommand = "mkdir -p database && touch database/database.sqlite && php artisan migrate --force"

startCommand = "php artisan serve --host=0.0.0.0 --port ${PORT}"

healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "always"
